# Generated by Django 5.2.8 on 2025-12-15 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_userinfo_sex_useraction'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='cover_url',
            field=models.URLField(blank=True, max_length=255, null=True, verbose_name='封面链接'),
        ),
    ]

