# Generated by Django 5.2.8 on 2025-12-17 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_userinfo_sex_useraction'),
        ('myapp', '0006_useraction_comment'),
    ]

    operations = [
    ]
